# Creating Namespace for Roboshop
########################################
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: roboshop
#   labels:
#     environment: development
#     project: roboshop

apiVersion: v1
kind: Namespace
metadata:   
  name: roboshop
  labels:
    project: roboshop
    environment: development







