apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    project: roboshop
    component: frontend
    environment: development
    version: v1
spec:
    containers:
    - name: frontend
      image: nginx