# kind: Pod
# apiVersion: v1
# metadata:
#   name: env-demo
# spec:
#   containers:
#   - name: nginx
#     image: nginx
#     env:
#     - name: course
#       value: kubernetes
#     - name: trainer
#       value: sivakumar

apiVersion: v1
kind: Pod
metadata:
  name: env-demo
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: course
      value: kubernetes
    - name: trainer
      value: kiran