# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-lb
# spec:
#   type: LoadBalancer
#   selector:
#     project: roboshop
#     component: frontend
#     environment: dev
#     purpose: load-balancer
#   ports:
#     - protocol: TCP
#       port: 80 # service port
#       targetPort: 80 # container port
#       nodePort: 30007 

apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  selector:
    project: roboshop
    component: frontend
    environment: dev
    purpose: load-balancer

  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007